feat: BaseLogger 추가
moonimooni/hm-exp pull request #13
Opened 2022-03-08 15:31 UTC by jeewonn

# What's changed?
- 로깅 파일 작성 (winston과 winston-daily-rotate-file 라이브러리를 추가 하였습니다.)
- .ignore에 logs 폴더 추가

# Why did you make this change?

# Please share your test code result!

이번엔도 package-lock.json 폴더가 수정된것같습니다.
제 문제점이 무엇일까요..?

2022-03-08 16:13 UTC, moonimooni commented
무슨일이 있었는진 모르겠지만 package-lock.json이 엄청 바뀌었나보네요.. 빌드 테스트도 실패하고 있습...😅

2022-03-08 19:17 UTC, jeewonn commented
말씀해주신...무식한 방법인 upstream develop 브랜치 package-lock.json 파일을 복붙 해보았습니다..

2022-03-08 19:48 UTC, jeewonn commented
제가 npm install winston, winston-daily-rotate-file 을 설치 했으니깐
package-lock.json이 바뀌어야 하는게 맞지 않나요?

새로운 라이브러리를 설치할때마다 package-lock.json도 같이 업데이트 되어야 하는거 아닌가요?

2022-03-08 22:26 UTC, redgpcmffld commented
> 제가 npm install winston, winston-daily-rotate-file 을 설치 해서 package-lock.json이 바뀐것같습니다.
> 
> 새로운 라이브러리를 설치할때마다 package-lock.json도 같이 업데이트 되어야 하는거 아닌가요?

네 package-lock.json 바뀌면 걔도 같이 커밋해주셔야 할거 같습니다

2022-03-09 09:25 UTC, jeewonn commented
> > 제가 npm install winston, winston-daily-rotate-file 을 설치 해서 package-lock.json이 바뀐것같습니다.
> > 새로운 라이브러리를 설치할때마다 package-lock.json도 같이 업데이트 되어야 하는거 아닌가요?
> 
> 네 package-lock.json 바뀌면 걔도 같이 커밋해주셔야 할거 같습니다

2022-03-09 09:39 UTC, jeewonn commented
winston, winston-daily-rotate-file을 다시 npm install 해서, package-lock.json을 업데이트 해주었는데,
빌드를 실패하여, `Caused by: Error: Cannot find module 'postcss-html'` 라고 에러 메시지를 확인 후 
postcss-html 를 install 하였습니다.

postcss-html 까지 install 해주니 빌드 실패가 안뜨네요!

2022-03-09 12:41 UTC, moonimooni requested changes
설치된 모듈이 dependent 하는 모듈을 못 불러와서 저희 서버에 dependency를 직접 추가하는게 맞는걸까요,,? 
각 모듈들은 package-lock.json의 트리구조에 맞춰서 각자의 node_modules를 가지고 있습니다. 거기서 문제가 생긴 것이니 변형된 package-lock.json을 고치는게 맞는 것 같습니다.

일단 문제점을 찾아야 하는데...
develop 브랜치의 package-lock.json을 불러와 `npm ci` 명령어 치신 후에, 
winston, winston-daily-rotate-file 패키지들을 하나하나 install 했을때 각 
package-lock.json의 어디가 얼마나 바뀌는지 확인해보셔야 할 것 같아요.
IDE의 source control로 확인해보시는걸 추천드립니다!

2022-03-09 14:54 UTC, jeewonn commented
> 설치된 모듈이 dependent 하는 모듈을 못 불러와서 저희 서버에 dependency를 직접 추가하는게 맞는걸까요,,? 각 모듈들은 package-lock.json의 트리구조에 맞춰서 각자의 node_modules를 가지고 있습니다. 거기서 문제가 생긴 것이니 변형된 package-lock.json을 고치는게 맞는 것 같습니다.
> 
> 일단 문제점을 찾아야 하는데... develop 브랜치의 package-lock.json을 불러와 `npm ci` 명령어 치신 후에, winston, winston-daily-rotate-file 패키지들을 하나하나 install 했을때 각 package-lock.json의 어디가 얼마나 바뀌는지 확인해보셔야 할 것 같아요. IDE의 source control로 확인해보시는걸 추천드립니다!

설치된 모듈이 dependent 하는 모듈을 못 불러와서 저희 서버에 dependency를 직접 추가하는게 맞는걸까요,,?
=> 이 말씀을 이해 못한것같아요. 
postcss-html 직접 설치 했던 부분 말씀하시는걸까요..?

2022-03-14 14:43 UTC, moonimooni approved these changes
go go go

2022-03-14 14:51 UTC, merged